config/routes.rb
App::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :user_steps

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
    
  match '/signup',  to: 'users#new',            via: 'get'
  
  root :to => 'high_voltage/pages#show', id: 'splash'
  

end

app/models/account_category.rb
class AccountCategory < ActiveRecord::Base
  belongs_to :user
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
end

app/models/social_account.rb
class SocialAccount < ActiveRecord::Base
  belongs_to :user
  before_save :normalize_blank_values

  def normalize_blank_values
    attributes.each do |column, value|
      self[column].present? || self[column] = nil
    end
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create { generate_token(:remember_token) }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  validates :password, presence: true, on: :create
  validates :password, length: { minimum: 6, maximum: 120 }, allow_blank: true, confirmation: true
  
  validates :alias, presence: true
  
  has_one :social_account
  accepts_nested_attributes_for :social_account
  
  has_many :videos
  accepts_nested_attributes_for :videos, allow_destroy: true
  
  has_one :account_category
  accepts_nested_attributes_for :account_category
  
  has_one :game
  accepts_nested_attributes_for :game
    
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  
  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = User.encrypt(User.new_token)
    end while User.exists?(column => self[column])
    self[column]
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  layout 'sm_app'
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    user.send_password_reset if user
    redirect_to new_password_reset_path, :notice => "Please check your email for password reset instructions."
  end
  
  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end
  
  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 1.hours.ago
      redirect_to new_password_reset_path, :alert => "Reset token has expired. Please send a new reset request."
    elsif @user.update_attributes(params[:user].permit(:password, :password_confirmation))
      redirect_to root_url, :notice => "Your password has been successfully reset."
    else
      render :edit
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in(user, params[:session][:remember_me])
      redirect_to :back
    else
      flash[:error] = "<div class='warning-box'>Invalid credentials</div>"
      redirect_to :back
    end
  end

  def destroy
    sign_out
    redirect_to :back
  end
end

app/controllers/user_steps_controller.rb
class UserStepsController < ApplicationController
  include Wicked::Wizard
  steps :account_type, :choose_game
  layout 'signup'
  
  def show
    @user = current_user
    @account = @user.build_account_category unless @user.account_category
    render_wizard
  end
  
  def update
    @user = current_user
    @user.update_attributes(user_params)
    @game = @user.build_game unless @user.game
    render_wizard @user
  end
  
  private
  def finish_wizard_path
    user_path(current_user)
  end
  
  def user_params
    params.require(:user).permit(account_category_attributes: [:id, :category],
                                 game_attributes: [:id, :name])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @social = @user.social_account
  end
  
  def new
    @user = User.new
    render :layout => 'signup'
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user, 1)
      redirect_to user_steps_path
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to signup_path
    end
  end
  
  def edit
    @user = User.find(params[:id])
    if @user.social_account
      @social = @user.social_account
    else
      @social = @user.build_social_account
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
    
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :alias,
                                 social_account_attributes: [:id, :facebook_url, :twitter_url, :stream_url],
                                 videos_attributes: [:id, :url, :_destroy],
                                 account_category_attributes: [:id, :category],
                                 game_attributes: [:id, :name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user, remember_me)
    remember_token = user.generate_token(:remember_token)
    if remember_me == "1"
      cookies.permanent[:remember_token] = remember_token
    else
      cookies[:remember_token] = remember_token
    end
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end
    
  def signed_in?
    !current_user.nil?
  end
    
  def current_user=(user)
    @current_user = user
  end
    
  def current_user
    return nil unless cookies[:remember_token]
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
    
  def sign_out
    current_user.update_attribute(:remember_token, nil)
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/user_steps_helper.rb
module UserStepsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_auth.html.erb
<div id="auth">
    <%= raw flash[:error] %>
    <div id="auth-logo">
        <%= image_tag "gg-logo.png" %>
    </div>
    <div id="auth-form">
        <%= form_for(:session, url: sessions_path) do |f| %>
            <%= f.text_field :email, :placeholder => "Email" %>
            <%= f.password_field :password, :placeholder => "Password" %>

			<div id="auth-remember-section">
                <label>
                    <%= f.check_box :remember_me %>
                    <i class="fa fa-square-o fa-fw"></i>Remember me
                </label>
            </div>
            <%= f.submit "Sign in", :class => "green-sm-btn" %>
        <% end %>
        <span>
            <%= link_to "Create an account", "/signup" %><%= link_to "Forgot password?", "#" %>
        </span>
    </div>

</div>

app/views/layouts/_dropdown_header.html.erb
<div id="dropdown-header-bkg">
    <div>
        <div id="dropdown-summary">
            <h6>SUMMARY</h6>
            <div>
                <%= image_tag "white-square.png", :class => "circle"  %>
            </div>
            <div>
                <div id="summary-name"><a href="">Zack Elliott</a></div>
                <div id="summary-account">Player Account<a href="">Change<i class="fa fa-angle-right"></i></a></div>
            </div>
        </div>
        <div id="dropdown-account">
            <i class="fa fa-times clickable toggle-dropdown-header"></i>
            <h6>ACCOUNT</h6>
            <div>
                <%= link_to current_user do %>
                    <i class="fa fa-user"></i>My Profile
                <% end %>
            </div>
            <div>
                <%= link_to '#' do %>
                    <i class="fa fa-cog"></i>Settings
                <% end %>
            <div>
            </div>
                <%= link_to signout_path, method: :delete do %>
                    <i class="fa fa-sign-out"></i>Logout
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
    <div>
        <%= image_tag("gg-logo-666.png") %>
        <p>Geeg.ee is a professional esports network that connects teams to new talent.</p>
    </div>
    <div>
        <h4>Us</h4>
        <ul>
            <li><%= link_to "About", page_path(id: 'about') %></li>
            <li><%= link_to "Blog", "http://ggdeck.tumblr.com/" %></li>
            <li><%= link_to "Team", page_path(id: 'team') %></li>
            <li><%= mail_to "hello@geegee.com", "Contact" %></li>
        </ul>
    </div>
    <div>
        <h4>Info</h4>
        <ul>
            <li><%= link_to "Privacy", "#" %></li>
            <li><%= link_to "Terms", page_path(id: 'terms') %></li>
        </ul>
    </div>
    <div>
        <h4>Social</h4>
        <ul>
            <li><%= link_to "Facebook", "#" %></li>
            <li><%= link_to "Twitter", "#" %></li>
            <li><%= link_to "Github", "#" %></li>
        </ul>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <%= link_to image_tag("gg-logo.png"), "#", :id => "logo" %>
    <div id="header-search">
        <%= text_field_tag :search, params[:search], :placeholder => "Search for anything" %>
    </div>
    <nav id="header-right-nav">
        <ul id="header-nav-menu">
        <% if signed_in? %>
            <li class="clickable toggle-dropdown-header">
                Zack<i id="dropdown-header-arrow" class="fa fa-caret-down"></i>
            </li>
        <% else %>
            <li id="signin" class="clickable" onclick="showSignIn();">Sign in</li>
            <%  if flash[:error] %>
                <%= javascript_tag do %>
                    showSignIn();
                <% end %>
            <% end %>
        <% end %>
        </ul>
    </nav>
</header>

app/views/layouts/_profile_header_personal.html.erb
<% content_for :profile_header do %>
    <div id="profile-header-bkg">
        <div>
            <span class="clickable"><i class="fa fa-pencil"></i>Edit your profile</span>
        </div>
    </div>
<% end %>

app/views/layouts/_profile_sidebar.html.erb
<div id="sidebar">
        <div id="connect-region">
            <div id="follow-region">
                <div class="green-sm-btn">
                    <i class="fa fa-plus-circle"></i>Connect
                </div>
            </div>
            <div id="contact-region">
                <div class="gray-sm-btn">
                    <i class="fa fa-envelope"></i>Contact
                </div>
            </div>
        </div>
        <div id="sidebar-info">
            <div id="permalink" class="sidebar-block">
                <input type="text" readonly="readonly" value="http://ggdeck.com/u/zackelliott" />
                <i class="fa fa-copy clickable"></i>
            </div>
            <div id="quick-info" class="sidebar-block">
                <h5>Info</h5>
                <ul>
                    <li>Age<span>18</span></li>
                    <li>Location<span>Seattle, WA</span></li>
                    <li>Languages<span>English, Spanish</span></li>
                </ul>
            </div>
            <div id="social-links" class="sidebar-block">
                <h5>Social Links</h5>
                <ul>
                    <li>Facebook<a href="">HubridNoxx's Page</a></li>
                    <li>Twitter<a href="">@hubridnoxx</a></li>
                    <li>Stream<a href="">HubridNoxx's Channel</a></li>
                </ul>
                <% if @social %>
                    <%= "Facebook:" + @social.facebook_url if @social.facebook_url  %>
                    <%= "Twitter:" + @social.twitter_url if @social.twitter_url %>
                    <%= "Stream:" + @social.stream_url if @social.stream_url %>
                <% end %>
            </div>
            <div id="related-players" class="sidebar-block">
                <h5>Related Players</h5>
                <ul>
                    <li>
                        <%= image_tag "small-white-square.png", :class => "circle" %>
                        <%= link_to "Zack Elliott", "#" %>
                        <small>Status of player</small>
                    </li>
                    <li>
                        <%= image_tag "small-white-square.png", :class => "circle" %>
                        <%= link_to "Hubrid Noxx", "#" %>
                        <small>Status of player</small>
                    </li>
                </ul>
            </div>
        </div>
    </div>

app/views/layouts/_sm_header.html.erb
<header>
    <%= link_to image_tag("gg-logo-333.png"), "#", :id => "logo" %>
    <nav id="header-right-nav">
        <ul id="header-nav-menu">
        <% if signed_in? %>
            <li class="clickable">
                <%= link_to "Zack", current_user %>
            </li>
        <% else %>
            <li id="signin" class="clickable" onclick="showSignIn();">Sign in</li>
            <%  if flash[:error] %>
                <%= javascript_tag do %>
                    showSignIn();
                <% end %>
            <% end %>
        <% end %>
        </ul>
    </nav>
</header>

app/views/layouts/_tall_header.html.erb
<header>
    <%= link_to image_tag("gg-logo-333.png"), "#", :id => "logo" %>
    <nav id="header-right-nav">
        <ul id="header-nav-menu">
        <% if signed_in? %>
            <li class="clickable">
                <%= link_to "Zack", current_user %>
            </li>
        <% else %>
            <li id="signin" class="clickable" onclick="showSignIn();">Sign in</li>
			<%  if flash[:error] %>
				<%= javascript_tag do %>
					showSignIn();
				<% end %>
			<% end %>
        <% end %>
        </ul>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Geeg.ee | </title>
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
        <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
        <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <%= render 'layouts/auth' %>
        <div id="darken-blur-wrapper" onclick="hideSignIn();"></div>
        <div id="blur-wrapper">
            <div id="wrapper">
                <div id="header-bkg">
                    <%= render 'layouts/header' %>
                </div>
                <%= render 'layouts/dropdown_header' %>
                <%= yield :about_header %>
                <%= yield :team_header %>
                <%= yield :contact_header %>
                <%= yield :privacy_header %>
                <%= yield :terms_header %>
                <%= yield :profile_header %>
                <div id="container">
                    <%= yield %>
                </div>
            </div>
            <div id="footer-bkg">
                <%= render 'layouts/footer' %>
            </div>
        </div>
    </body>
</html>

app/views/layouts/signup.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Geeg.ee | </title>
        <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
        <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <%= render 'layouts/auth' %>
        <div id="darken-blur-wrapper" onclick="hideSignIn();"></div>
        <div id="blur-wrapper">
            <div id="wrapper">
                <div id="tall-header-bkg">
                    <%= render 'layouts/tall_header' %>
                </div>
                <%= render 'layouts/dropdown_header' %>
                <div id="container">
                    <div class="signup-content">
                        <div class="signup-steps">
                            <ul>
                                <li class="active-step"><i class="fa fa-chevron-circle-right"></i>Sign up</li>
                                <li>Choose account</li>
                                <li>Select game</li>
                                <li>Create profile</li>
                            </ul>
                        </div>
                        <%= yield %>
                    </div>
                </div>
            </div>
            <div id="footer-bkg">
                <%= render 'layouts/footer' %>
            </div>
        </div>
    </body>
</html>

app/views/layouts/sm_app.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Geeg.ee | </title>
        <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
        <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
        <%= csrf_meta_tags %>
    </head>
    <body class="sm-app">
        <%= render 'layouts/auth' %>
        <div id="darken-blur-wrapper" onclick="hideSignIn();"></div>
        <div id="blur-wrapper">
            <div id="wrapper">
                <div id="header-bkg">
                    <%= render 'layouts/sm_header' %>
                </div>
                <div id="container">
                    <div class="sm-app-form">
                        <div class="sm-logo">
                            <%= image_tag "gg-logo-lg-3d.png" %>
                        </div>
                        <%= yield %>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

app/views/pages/about.html.erb
<% content_for :about_header do %>
    <div id="about-header-bkg">
    </div>
<% end %>

<div class="content">
    
</div>

app/views/pages/privacy.html.erb
<% content_for :privacy_header do %>
    <div id="privacy-header-bkg" class="sub-header">
        <div>
            <span class="header-desc">Legal</span>
            <span class="header-title">Privacy</span>
        </div>
    </div>
<% end %>

app/views/pages/team.html.erb
<% content_for :team_header do %>
    <div id="team-header-bkg" class="sub-header">
        <div>
            <span class="header-desc">Meet the people behind the scenes</span>
            <span class="header-title">Team</span>
        </div>
    </div>
<% end %>

<div class="content">
    <div class="team-member">
        <div class="member-picture">
            <%= image_tag("white-square.png") %>
        </div>
        <div class="member-info">
            <h1 class="member-name">Zack Elliott</h1>
            <h2 class="member-title">Co-Founder / Lead Front End Dev</h2>
            <p class="member-story">Zack is a student at The Wharton School at the University of Pennsylvania, where he is studying Economics and Computer Science.  He first came up with the idea of Geeg.ee while (jokingly) wishing he could put his eSports MMR on his LinkedIn account.  He hopes GGDeck will help connect rising players to new teams and foster growth in the esports scene.</p>
            <div class="member-links">
                <a href="http://www.linkedin.com/in/zackelliott/"><i class="fa fa-linkedin"></i></a>
                <a href="http://github.com/HubridNoxx"><i class="fa fa-github"></i></a>
                <a href="http://stackoverflow.com/users/831938/hubrid"><i class="fa fa-stack-exchange"></i></a>
            </div>
        </div>
    </div>
    
    <div class="team-member">
        <div class="member-picture">
            <%= image_tag("white-square.png") %>
        </div>
        <div class="member-info">
            <h1 class="member-name">Gaurav Jhaveri</h1>
            <h2 class="member-title">Co-Founder / Lead Back End Dev</h2>
            <p class="member-story">Gaurav is currently an undergraduate studying Computer Science at the Vidyalankar Institute of Technology. He's very passionate about eSports and sees it as a viable career choice. Working on Geeg.ee allows him to combine his love of programming and eSports into a single project.</p>
            <div class="member-links">
                <a href="http://www.linkedin.com/in/gauravjhaveri"><i class="fa fa-linkedin"></i></a>
                <a href="https://github.com/Mutinix"><i class="fa fa-github"></i></a>
                <a href="https://twitter.com/gaurav_jhaveri"><i class="fa fa-twitter"></i></a>
            </div>
        </div>
    </div>
</div>

app/views/pages/terms.html.erb
<% content_for :terms_header do %>
    <div id="terms-header-bkg" class="sub-header">
        <div>
            <span class="header-desc">Legal</span>
            <span class="header-title">Terms</span>
        </div>
    </div>
<% end %>

app/views/password_resets/edit.html.erb
<% if @user.errors.any? %>
    <div class="warning-box">
        <% for message in @user.errors.full_messages %>
            <div><%= message %></div>
        <% end %>
    </div>
<% end %>

<div class="forgot-title">
    Change Password
</div>
<div class="forgot-desc">
    Choose a new password for your account.
</div>

<%= form_for @user, :url => password_reset_path(params[:id]), :method => :put do |f| %>

    <%= f.password_field :password, placeholder: "New Password" %>
    <%= f.password_field :password_confirmation, placeholder: "Confirm New Password" %>
    <%= f.submit 'Update Password', :class => "green-sm-btn update-pass-btn" %>
<% end %>

app/views/password_resets/new.html.erb
<% flash.each do |key, value| %>
    <div class="warning-box">
        <%= content_tag(:div, value, :class => "flash #{key}") %>
    </div>
<% end %>

<div class="forgot-title">
    Forgot password
</div>
<div class="forgot-desc">
    Enter your email and we'll send you instructions to reset your password.
</div>
<%= form_tag password_resets_path, :method => :post do %>
    <%= text_field_tag :email, nil, placeholder: "Email" %>
    <%= submit_tag "Reset Password", :class => "green-sm-btn reset-pass-btn" %>
    <span>
        <%= link_to "Return to login", "#" %>
    </span>
<% end %>

app/views/user_steps/account_type.html.erb
<%= form_for current_user, url: wizard_path do |f| %>
    <div class="selection-frame">
        <div class="page-header">
            <div>Choose an account</div>
            <span class="clickable tooltip" title="You might fit more than one role here.  Choose your primary role, the account type is less of a strict categorization and more of a soft focus.  You can always change later.">Not sure which?</span>
        </div>
        <div class="account-types">
            <div class="player-acc clickable">
                <div class="account-header">
                    <i class="fa fa-gamepad fa-3x"></i>
                    <div>Player</div>
                </div>
                <div class="account-desc">
                    <ul class="fa-ul">
                      <li><i class="fa-li fa fa-check"></i>Demonstrate your skills</li>
                      <li><i class="fa-li fa fa-check"></i>Build a gaming resume</li>
                      <li><i class="fa-li fa fa-check"></i>Connect with teams</li>
                    </ul>
                </div>
            </div>
            <div class="caster-acc clickable">
                <div class="account-header">
                    <i class="fa fa-microphone fa-3x"></i>
                    <div>Caster</div>
                </div>
                <div class="account-desc">
                    <ul class="fa-ul">
                      <li><i class="fa-li fa fa-check"></i>Showcase your videos</li>
                      <li><i class="fa-li fa fa-check"></i>Connect with viewers</li>
                      <li><i class="fa-li fa fa-check"></i>Discover casting abilities</li>
                    </ul>
                </div>
            </div>
            <!--<div class="org-acc clickable">
                <div class="account-header">
                    <i class="fa fa-globe fa-3x"></i>
                    <div>Organization</div>
                </div>
                <div class="account-desc">
                    <ul class="fa-ul">
                      <li><i class="fa-li fa fa-check"></i>Promote your content</li>
                      <li><i class="fa-li fa fa-check"></i>Understand your audience</li>
                      <li><i class="fa-li fa fa-check"></i>Connect with gamers</li>
                    </ul>
                </div>
            </div>-->
        </div>
    </div>
    <%= f.radio_button :name, 'player', :checked => true %>
    <%= f.radio_button :name, 'caster' %>
    <%= f.submit "Continue", :class => "green-sm-btn user-steps-continue" %>
<% end %>

app/views/user_steps/choose_game.html.erb
<%= form_for current_user, url: wizard_path do |f| %>
    <div class="selection-frame">
        <div class="page-header">
            <div>Select your game</div>
            <span class="clickable tooltip" title="We know you might play more than one game, but right now users are limited to a single one.  In the future, we will enable multiple games per account.">Not sure which?</span>
        </div>
        <div class="game-types">
            <div class="league-acc clickable">
                <div class="account-header">
                    <i class="fa fa-angle-down fa-3x"></i>
                    <div>LoL</div>
                </div>
                <div class="game-pic">
                    <%= image_tag("select-game-artwork/select-game-league.jpg") %>
                </div>
            </div>
            <div class="dota-acc clickable">
                <div class="account-header">
                    <i class="fa fa-angle-down fa-3x"></i>
                    <div>Dota 2</div>
                </div>
                <div class="game-pic">
                    <%= image_tag("select-game-artwork/select-game-dota.jpg") %>
                </div>
            </div>
            <div class="starcraft-acc clickable">
                <div class="account-header">
                    <i class="fa fa-angle-down fa-3x"></i>
                    <div>Starcraft 2</div>
                </div>
                <div class="game-pic">
                    <%= image_tag("select-game-artwork/select-game-starcraft.jpg") %>
                </div>
            </div>
        </div>
    </div>
    <%= f.radio_button :name, 'lol', :checked => true %>
    <%= f.radio_button :name, 'dota' %>
    <%= f.radio_button :name, 'starcraft' %>
    <%= f.submit "Continue", :class => "green-sm-btn user-steps-continue" %>
<% end %>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>

  <%= f.label :alias %>
  <%= f.text_field :alias %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirm Password" %>
  <%= f.password_field :password_confirmation %>
  
  
  Social Media
  <%= f.fields_for :social_account do |social_form| %>
      <%= social_form.label :facebook %>
      <%= social_form.text_field :facebook_url %>
      
      <%= social_form.label :twitter %>
      <%= social_form.text_field :twitter_url %>
      
      <%= social_form.label :stream %>
      <%= social_form.text_field :stream_url %>
  <% end %>
  
  <br>
  
  Featured Videos
  <div class="items">
      <%= f.nested_fields_for :videos do |f| %>
        <fieldset class="item">
          <%= f.label :Video %>
          <%= f.text_field :url %>

          <a href="#" class="remove">Remove</a>

          <%= f.hidden_field :id %>
          <%= f.hidden_field :_destroy %>
        </fieldset>
      <% end %>
    </div>
    <a href="#" class="add">Add Video</a>
  

  <%= f.submit "Update Profile" %>
<% end %>

app/views/users/new.html.erb
<div class="signup-frame">
    <div class="signup-banner">
        <%= image_tag "gg-logo-lg-3d.png", :class => "banner-logo" %>
        <div class="banner-motto">Your professional esports network.</div>
    </div>
    <div>
        <div class="warning-box">
            <% if flash[:errors] %>
                <% flash[:errors].each do |e| %>
                    <div><%= e %></div>
                <% end %>
            <% end %>
        </div>
        <%= form_for(@user) do |f| %>
        <%= f.text_field :name, placeholder: "Full name" %>        
        <%= f.text_field :alias, placeholder: "Alias" %>
        <%= f.text_field :email, placeholder: "Email" %>  
        <%= f.password_field :password, placeholder: "Password" %>  
        <%= f.password_field :password_confirmation, placeholder: "Confirm password" %>
        <%= f.submit "Sign up" %>
        <% end %>
        <div class="form-note">
            By clicking this button you agree to GGDeck's <%= link_to "Terms and Conditions", page_path(id: 'terms') %>
        </div>
    </div>
</div>